services:
  - type: web
    name: discord-turk
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_GIZLI_ANAHTAR
        generateValue: true
    autoDeploy: true